[DRUP-784] Fix drush si for non-interactive install
apigee/apigee-devportal-kickstart-drupal pull request #107
Opened 2019-05-08 18:03 UTC by arshad

This PR fixes site install via `drush si`. It hides the Edge configuration install task if site is installed non-interactively.

Use the following command to install the site and create an edge connection key:

`drush si apigee_devportal_kickstart --account-name=admin --account-pass=admin --account-mail='admin@example.com' --site-name='Apigee' --site-mail='admin@example.com' --db-url=mysql://root:root@localhost/database --uri=http://kickstart.test -y; drush key-save apigee_edge_connection_default '{\"auth_type\":\"basic\",\"organization\":\"ORGANIZATION\",\"username\":\"USERNAME\",\"password\":\"PASSWORD\"}' --key-type=apigee_auth -y`

2019-05-08 18:32 UTC, cnovak requested changes
This PR is missing update of docs & quick-start composer command. We need to update docs to use the above command and remove quick-start from composer and update readme, or update quick-start script in composer and update docs on how the user should set up edge org after running quick start if they want to see keys working.  If we change docs, we also need to change README on  https://github.com/apigee/devportal-kickstart-project-composer and kickstart Drupal project page.

2019-05-08 19:42 UTC, jacine commented
Quick update: I've tested this, and while I'm still having Drush issues, this PR fixes `composer quick-start`.

2019-05-08 21:59 UTC, jacine commented
Ok, back with confirmation that:

1. This fixes the `composer quick-start` command.  See the output below. The installer works, and the user is just lacking an Apigee Edge connect. 
2. Drush is still broken. The command above is not working for me. And we've been trying to figure this out all afternoon without success. @daweher has been helping, and has suggested doing this another way. This will be looked at tomorrow.

So, do we want to merge this (since it fixes quick-start)?  And come back to the Drush issue separately?

I'll also work on adding a note to the documentation to the README, pointing to the [documentation](https://www.drupal.org/docs/8/modules/apigee-edge/configure-the-connection-to-apigee-edge) tomorrow as @cnovak requested.

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> DrupalComposer\DrupalScaffold\Plugin::scaffold
  - .csslintrc (https://git.drupalcode.org/project/drupal/raw/8.7.1/.csslintrc): Downloading (100%)
  - .editorconfig (https://git.drupalcode.org/project/drupal/raw/8.7.1/.editorconfig): Downloading (100%)
  - .eslintignore (https://git.drupalcode.org/project/drupal/raw/8.7.1/.eslintignore): Downloading (100%)
  - .eslintrc.json (https://git.drupalcode.org/project/drupal/raw/8.7.1/.eslintrc.json): Downloading (100%)
  - .gitattributes (https://git.drupalcode.org/project/drupal/raw/8.7.1/.gitattributes): Downloading (100%)
  - .ht.router.php (https://git.drupalcode.org/project/drupal/raw/8.7.1/.ht.router.php): Downloading (100%)
  - .htaccess (https://git.drupalcode.org/project/drupal/raw/8.7.1/.htaccess): Downloading (100%)
  - index.php (https://git.drupalcode.org/project/drupal/raw/8.7.1/index.php): Downloading (100%)
  - robots.txt (https://git.drupalcode.org/project/drupal/raw/8.7.1/robots.txt): Downloading (100%)
  - sites/default/default.services.yml (https://git.drupalcode.org/project/drupal/raw/8.7.1/sites/default/default.services.yml): Downloading (100%)
  - sites/default/default.settings.php (https://git.drupalcode.org/project/drupal/raw/8.7.1/sites/default/default.settings.php): Downloading (100%)
  - sites/development.services.yml (https://git.drupalcode.org/project/drupal/raw/8.7.1/sites/development.services.yml): Downloading (100%)
  - sites/example.settings.local.php (https://git.drupalcode.org/project/drupal/raw/8.7.1/sites/example.settings.local.php): Downloading (100%)
  - sites/example.sites.php (https://git.drupalcode.org/project/drupal/raw/8.7.1/sites/example.sites.php): Downloading (100%)
  - update.php (https://git.drupalcode.org/project/drupal/raw/8.7.1/update.php): Downloading (100%)
  - web.config (https://git.drupalcode.org/project/drupal/raw/8.7.1/web.config): Downloading (100%)
> php web/core/scripts/drupal quick-start apigee_devportal_kickstart
 0/20 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]
Installing Apigee Developer Portal Kickstart

 1/20 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]
Choose profile

 2/20 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]
Choose profile

 3/20 [▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░]
Verify requirements

 4/20 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]
Set up database

 5/20 [▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░]
Set up database

 6/20 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]
Set up database

 7/20 [▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░]
Set up database

 8/20 [▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░]
Set up database

 9/20 [▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░]
Install site

10/20 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░]
Install site

11/20 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░]
Install site

12/20 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░]
Configure site

13/20 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░]
Install demo content

14/20 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░]
Install theme

15/20 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░]
Install theme

16/20 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░]
Install theme

16/20 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░]
Congratulations, you installed Apigee Developer Portal Kickstart!

20/20 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓]
Congratulations, you installed Apigee Developer Portal Kickstart!
Username: admin
Password: EpdP6nNapwpi_VUH
Drupal development server started: <http://127.0.0.1:8888>
This server is not meant for production use.
One time login url: <http://127.0.0.1:8888/user/reset/1/1557351539/023b9hCIA3bgBni8oi3Uq1UKF89jd17SPwL8Ftxkqr0/login>
Press Ctrl-C to quit the Drupal development server.
```

2019-05-08 22:23 UTC, cnovak commented
The biggest issue is quick-start, so we can approve this now, thanks!

2019-05-08 22:23 UTC, cnovak approved these changes

2019-05-08 22:35 UTC, cnovak commented
@jacine test above shows that this PR will fix #98

2019-05-09 00:13 UTC, merged

2019-07-16 17:18 UTC, jacine commented
This is working now.  Here's a working example (tested w/Drush 9):

`drush sql-drop -y; drush si apigee_devportal_kickstart --account-name=admin --account-pass=admin --site-name='SITE NAME' --account-mail='APIGEE_EMAIL' --site-mail='APIGEE_EMAIL' --db-url=mysql://root:root@localhost/DATABASE --uri=https://SITE_URI -y; drush key-save apigee_edge_connection_default '{"auth_type":"basic","organization":"APIGEE_ORG","username":"APIGEE_EMAIL","password":"APIGEE_PASSWORD"}' --key-type=apigee_auth -y; drush --uri=https://SITE_URI uli`