[DRUP-767] Dropbutton
apigee/apigee-devportal-kickstart-drupal pull request #113
Opened 2019-05-17 15:10 UTC by jacine

## Closed
<img width="319" alt="dropbutton" src="https://user-images.githubusercontent.com/60979/57937621-4931bc80-7894-11e9-9aac-40eaa5c7b61e.png">

## Open
<img width="304" alt="dropbutton-open" src="https://user-images.githubusercontent.com/60979/57937630-4afb8000-7894-11e9-8eb0-672556af0b9e.png">

2019-05-21 10:57 UTC, shadcn requested changes
This looks good. Can we make two small changes?

1. Add a hover style for the dropdown links.
2. Do we need a separator? Right now it looks like one button.

Thanks @jacine

2019-05-21 16:09 UTC, jacine commented
> This looks good. Can we make two small changes?
> 
> 1. Add a hover style for the dropdown links.
> 2. Do we need a separator? Right now it looks like one button.
> 
> Thanks @jacine

Yah, I was really just following the designs here... But it might be worth going back to the designer here to make this a little bit better.

2019-05-23 20:18 UTC, jacine commented
## New Dropbutton 🆕 

Thank you @rogerstrunk! 😄 👏 

### Default State
<img width="290" alt="Screen Shot 2019-05-23 at 4 12 12 PM" src="https://user-images.githubusercontent.com/60979/58283124-8d7dfa80-7d75-11e9-8c7d-a1a88fab9baa.png">

### Expanded, hovering on the button
<img width="202" alt="Screen Shot 2019-05-23 at 4 17 21 PM" src="https://user-images.githubusercontent.com/60979/58283466-58be7300-7d76-11e9-94dc-e20e5c292e8f.png">

### Expanded, hovering on a secondary action.
<img width="195" alt="Screen Shot 2019-05-23 at 3 06 40 PM" src="https://user-images.githubusercontent.com/60979/58283136-92db4500-7d75-11e9-8cc6-dc9f031ef671.png">

2019-05-24 11:02 UTC, shadcn approved these changes

2019-05-24 11:02 UTC, merged