ApigeeX code to show the monetization step during installation
apigee/apigee-devportal-kickstart-drupal pull request #497
Opened 2021-07-26 12:55 UTC by divya-intelli

This PR will show the monetization step along with option to enable add credit module during installation for monetized ApigeeX org.

2021-08-17 15:06 UTC, giteshk requested changes

2021-08-17 15:06 UTC, giteshk commented on composer.json
> +        "ApigeeX supported currency": "https://patch-diff.githubusercontent.com/raw/divya-intelli/apigee-client-php/pull/4.diff"
Why are we not merging this into the main library?

2021-08-18 07:55 UTC, divya-intelli commented on composer.json
> +        "ApigeeX supported currency": "https://patch-diff.githubusercontent.com/raw/divya-intelli/apigee-client-php/pull/4.diff"
Once we get a go ahead , feature-ngmint-phase2 branch will be merged to master branch, till then the PR's will be merged to feature-ngmint-phase2 branch.

2021-09-09 14:37 UTC, raakesh-blokhra approved these changes
LGTM

2021-09-09 14:39 UTC, raakesh-blokhra approved these changes
LGTM

2021-09-09 14:40 UTC, raakesh-blokhra approved these changes
LGTM

2021-09-09 14:43 UTC, merged